/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "primary": "#bec6e0",
        "secondary-container": "#604403",
        "tertiary-container": "#081828",
        "inverse-primary": "#565e74",
        "on-primary-container": "#798098",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "inverse-on-surface": "#263143",
        "on-surface": "#d8e3fb",
        "on-secondary-container": "#dab36a",
        "outline": "#909097",
        "outline-variant": "#45464d",
        "on-primary-fixed": "#131b2e",
        "on-tertiary": "#233143",
        "on-secondary": "#412d00",
        "primary-fixed-dim": "#bec6e0",
        "on-error": "#690005",
        "secondary": "#e9c176",
        "tertiary": "#b9c8de",
        "inverse-surface": "#d8e3fb",
        "on-secondary-fixed": "#261900",
        "tertiary-fixed-dim": "#b9c8de",
        "surface-container-low": "#111c2d",
        "surface-variant": "#2a3548",
        "surface-tint": "#bec6e0",
        "secondary-fixed": "#ffdea5",
        "primary-fixed": "#dae2fd",
        "surface-dim": "#081425",
        "on-primary": "#283044",
        "primary-container": "#0f172a",
        "on-tertiary-container": "#738296",
        "on-surface-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#5d4201",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-highest": "#2a3548",
        "on-tertiary-fixed-variant": "#39485a",
        "on-tertiary-fixed": "#0d1c2d",
        "surface-container-high": "#1f2a3c",
        "surface-container-lowest": "#040e1f",
        "surface": "#081425",
        "on-background": "#d8e3fb",
        "tertiary-fixed": "#d4e4fa",
        "surface-container": "#152031",
        "background": "#081425",
        "surface-bright": "#2f3a4c",
        "secondary-fixed-dim": "#e9c176",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "margin-edge": "64px",
        gutter: "32px",
        "container-max": "1280px",
        "section-gap": "120px",
      },
      fontFamily: {
        button: ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-caps": ["Inter"],
        "display-hero": ["Inter"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        button: ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["30px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
